--- #Configuration for creating an atlas from OSM data
#boundary:
#  north: 48.27 #degrees latitude
#  south: 48.22
#  east: 16.37 #degrees longitude
#  west: 16.25
zoomLevel: 15
overviewZoomLevel: 13
scale: 20000 #scale: x is a scale of 1/x


cachePath: cache

paper:
  size: a4 #a0-a6
  orientation: portrait #portrait or landscape
  margin: 3 #Empty space at edge of page (in mm)
  overlap: 8 #How much of the edge should be shared with the next page (in mm)

title: Wien
dontSwitchPageNumbering: false
pageNumberOffset: 0
evenLeftNumbering: false
addBlankPage: false
omitTitlePage: false



#Non-retina:
sourceURL: https://tile.openstreetmap.org/{z}/{x}/{y}.png #standard tiles
#sourceURL: https://tile.openstreetmap.de/{z}/{x}/{y}.png #german style

#Retina:
#sourceURL: https://tile.osmand.net/hd/{z}/{x}/{y}.png
#sourceURL: https://tiles.bergfex.at/styles/bergfex-osm/{z}/{x}/{y}@2x.png #bergfex with amenities