--- #Configuration for creating an atlas from OSM data
boundary:
  north: 48.27 #degrees latitude
  south: 48.22
  east: 16.37 #degrees longitude
  west: 16.25
zoomLevel: 16
overviewZoomLevel: 13
scale: 10000 #scale: x is a scale of 1/x

sourceURL: https://tile.osmand.net/hd/{z}/{x}/{y}.png
cachePath: cache

paper:
  size: a4 #a0-a6
  orientation: portrait #portrait or landscape
  margin: 3 #Empty space at edge of page (in mm)
  overlap: 8 #How much of the edge should be shared with the next page (in mm)

dontSwitchPageNumbering: false
pageNumberOffset: 0
evenLeftNumbering: true
addBlankPage: false
omitTitlePage: true